USE EMPLOYEE_TRACKER;


CREATE TABLE IF NOT EXISTS `DEPARTMENT` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DEPARTMENT_NAME` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB


CREATE TABLE IF NOT EXISTS `ROLE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ROLE_TITLE` VARCHAR(30) NOT NULL,
  `ROLE_SALARY` DECIMAL NOT NULL,
  `DEPARTMENT_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_ROLE_DEPARTMENT1_idx` (`DEPARTMENT_ID` ASC),
  CONSTRAINT `fk_ROLE_DEPARTMENT1`
    FOREIGN KEY (`DEPARTMENT_ID`)
    REFERENCES `DEPARTMENT` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB

CREATE TABLE IF NOT EXISTS `EMPLOYEE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `FIRST_NAME` VARCHAR(30) NOT NULL,
  `LAST_NAME` VARCHAR(30) NOT NULL,
  `MANAGER_ID` INT NULL,
  `ROLE_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `MANAGER_ID_idx` (`MANAGER_ID` ASC),
  INDEX `fk_EMPLOYEE_ROLE1_idx` (`ROLE_ID` ASC),
  CONSTRAINT `MANAGER_ID`
    FOREIGN KEY (`MANAGER_ID`)
    REFERENCES `EMPLOYEE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_EMPLOYEE_ROLE1`
    FOREIGN KEY (`ROLE_ID`)
    REFERENCES `ROLE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
